"""camera heartbeat

Revision ID: 760beb713e8e
Revises: 5b354c3d999e
Create Date: 2026-10-10 09:49:15.908596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "760beb713e8e"
down_revision: Union[str, Sequence[str], None] = "5b354c3d999e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cameras", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "last_seen_at")
    # ### end Alembic commands ###
